---
- name: Common tasks FTW
  hosts: all
  become: yes
  pre_tasks:
    - name: Set hostname
      hostname: name={{inventory_hostname}}

- name: Base panda service
  hosts: base
  become: yes
  roles:
    - { role: python3, tags: python3 }
    - { role: pip3, tags: pip3 }
    - { role: panda, tags: panda }
